### ISSUE TITLE
Please upgrade to > SonarQube 6.2 and > Keycloak 2.5.5

### ISSUE THREAD

**Issue by jaykeshur** [mnadeem/sonar-keycloak#1]

**Comment by mnadeem** [comment]
Let me see what can be done

**Comment by jfmoy** [comment]
Does it mean this plugin does not work at all on recent versions of Keycloak and SonarQube?

Thanks.

**Comment by jaykeshur** [comment]
Correct. It doesn't work.

**Comment by jaykeshur** [comment]
Any update on this @mnadeem ?

**Comment by andrejmaya** [comment]
have a look into https://github.com/vaulttec/sonar-auth-oidc @jaykeshur. It worked with Keycloak 3.4.0.Final and SonarQube 7.0

**Comment by jaykeshur** [comment]
Thanks @andrejmaya, we did exactly that a couple of months ago, but forgot to update this ticket :)
