### ISSUE TITLE
Add a licencse to the project

### ISSUE THREAD

**Issue by bs-matil** [mnadeem/sonar-keycloak#2]
Hello can you please add a license to the project? Otherwise its impossible to provide pull requests.

**Comment by mnadeem** [comment]
Done

**Comment by bs-matil** [comment]
Unfortunately the licencse you choosed is impossible as 
GNU LGPL
    The LGPL is ineligible primarily due to the restrictions it places on larger works, violating the third license criterion.


Please check
https://www.apache.org/legal/resolved.html#category-x

may you just add the GNU LGPL?

**Comment by mnadeem** [comment]
Added GNU Lesser General Public License v3.0
